modLoader="javafml" #mandatory
loaderVersion="${loader_version}" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/shock-metal/shock-metal/issues"


[[mods]] #mandatory
    modId="shockmetal" #mandatory
    version="${version}" #mandatory
    displayName="Shock Metal" #mandatory
    updateJSONURL="https://github.com/shock-metal/shock-metal/blob/master/version.json" #optional
    displayURL="https://github.com/shock-metal/shock-metal" #optional
    logoFile="shockmetal_logo.png" #optional
    credits="Forge Guys, CoFH Team" #optional
    authors="vNemesis_HD, Shockwave Interactive" #optional
    description='''Adds a new metal with at a level higher than diamond, Can be found in the nether but is rare.'''#mandatory

[[dependencies.shockmetal]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.shockmetal]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version}"
    ordering="NONE"
    side="BOTH"
