# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CD and Release

on:
  push:
    branches: [ 1.18.x ]

jobs:
  build:
    name: "🔨 Build Project"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
      
    - name: Read Props
      uses: madhead/read-java-properties@latest
      id: props
      with:
        file: gradle.properties
        all: true
      env:
        MOD_VERSION: '${{ steps.props.mc_version }}-${{ steps.props.mod_version }}'
        RELEASE_NAME: "Version $MOD_VERSION"
        JAR_NAME: '${{ steps.props.mc_version }}-${{ steps.props.mod_version }}.jar'
        JAR_PATH: './artifacts/${{ steps.props.mc_version }}-${{ steps.props.mod_version }}.jar'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Generate data
      run: ./gradlew :runData
      
    - name: Build with Gradle
      run: ./gradlew :build

    - name: Upload Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: "modJar"
        path: build/libs/
        retention-days: 7

  publish-release:
    name: "📘 Publish to Github Releases"
    runs-on: ubuntu-latest
    
    needs: [build]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        name: "modJar"
        path: ./artifacts

    - name: "✏️ Generate release changelog"
      id: changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        unreleasedOnly: true
        issueLineLabels: "Bug"
        
#    - name: Create GitHub Release
#      uses: actions/create-release@v1
#      continue-on-error: true
#      id: create_release
#      with:
#        draft: false
#        prerelease: false
#        release_name: $RELEASE_NAME
#        tag_name: $MOD_VERSION
#        body: ${{ steps.changelog.outputs.changelog }}
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#    - name: Add JAR to release
#      if: steps.create_release.outcome == 'success'
#      uses: actions/upload-release-asset@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: ${{ steps.create_release.outputs.upload_url }}
#        asset_path: $JAR_PATH
#        asset_name: $JAR_NAME
#        asset_content_type: application/octet-stream

    - name: Publish Files
      uses: Kir-Antipov/mc-publish@v2.1
      with:
        curseforge-id: 289438
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        
        github-tag: 1.18.2-1.2.0.1
        github-token: ${{ secrets.GITHUB_TOKEN }}

        files-primary: ./artifacts/!(*-@(dev|sources)).jar
        files-secondary: ./artifacts/*-@(dev|sources).jar

        name: ""
        version: $MOD_VERSION
        version-type: release
        changelog: ${{ steps.changelog.outputs.changelog }}

        loaders: |
          forge
        game-versions: |
          ${{ steps.props.mc_version }}

        java: |
          Java 17

        retry-attempts: 2
        retry-delay: 10000
